### ISSUE TITLE
Meu perfil

### ISSUE THREAD

**Issue by gabrielperuzzaufla** [Space-G/TrabalhoES2019-2#9]
RF003 & RF004 & RF010 & RF011 & RF012

**Comment by Space-G** [comment]
A gente vai guardar as fotos de perfil como arquivos de imagem, e no MySQL vamos apenas colocar o nome do arquivo (que será gerado aleatoriamente). 


Me incomoda permitir um upload de arquivo tão à mercê do usuário, preciso pesquisar se tem como alguém colocar um script malicioso em uma imagem.
